"""empty message

Revision ID: 189acb9ea14e
Revises: 26da5d58e57d
Create Date: 2013-11-26 21:10:29.927000

"""

# revision identifiers, used by Alembic.
revision = '189acb9ea14e'
down_revision = '26da5d58e57d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
