"""empty message

Revision ID: 235b0f1faf23
Revises: 4eaed1de260e
Create Date: 2013-11-23 17:27:23.073000

"""

# revision identifiers, used by Alembic.
revision = '235b0f1faf23'
down_revision = '4eaed1de260e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', u'slug')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column(u'slug', sa.VARCHAR(length=255), nullable=True))
    ### end Alembic commands ###
