"""empty message

Revision ID: 26da5d58e57d
Revises: 1e2db5b9c62c
Create Date: 2013-11-26 20:33:33.938000

"""

# revision identifiers, used by Alembic.
revision = '26da5d58e57d'
down_revision = '1e2db5b9c62c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('person_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'person_id')
    ### end Alembic commands ###
