"""empty message

Revision ID: 27a1055d2da2
Revises: 559df8c33b9b
Create Date: 2013-11-23 15:29:49.475000

"""

# revision identifiers, used by Alembic.
revision = '27a1055d2da2'
down_revision = '559df8c33b9b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
