"""empty message

Revision ID: 2e18f1c646f4
Revises: 27a1055d2da2
Create Date: 2013-11-23 15:59:52.308000

"""

# revision identifiers, used by Alembic.
revision = '2e18f1c646f4'
down_revision = '27a1055d2da2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
