"""empty message

Revision ID: 32da4f9df8b3
Revises: 3e43e9b1eb59
Create Date: 2013-11-23 16:05:15.369000

"""

# revision identifiers, used by Alembic.
revision = '32da4f9df8b3'
down_revision = '3e43e9b1eb59'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', u'person_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column(u'person_id', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###
