"""empty message

Revision ID: 36cea0b2c9cf
Revises: 189acb9ea14e
Create Date: 2013-11-26 21:21:30.511000

"""

# revision identifiers, used by Alembic.
revision = '36cea0b2c9cf'
down_revision = '189acb9ea14e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('person_name', sa.String(length=100), nullable=True))
    op.drop_column('articles', u'person_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column(u'person_id', sa.INTEGER(), nullable=True))
    op.drop_column('articles', 'person_name')
    ### end Alembic commands ###
