"""empty message

Revision ID: 3e43e9b1eb59
Revises: 2e18f1c646f4
Create Date: 2013-11-23 16:00:28.003000

"""

# revision identifiers, used by Alembic.
revision = '3e43e9b1eb59'
down_revision = '2e18f1c646f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
