"""empty message

Revision ID: 422af9a053ac
Revises: 531e0407a9a6
Create Date: 2013-11-29 23:16:05.922000

"""

# revision identifiers, used by Alembic.
revision = '422af9a053ac'
down_revision = '531e0407a9a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
