"""empty message

Revision ID: 4eaed1de260e
Revises: 32da4f9df8b3
Create Date: 2013-11-23 17:00:31.942000

"""

# revision identifiers, used by Alembic.
revision = '4eaed1de260e'
down_revision = '32da4f9df8b3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('slug', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'slug')
    ### end Alembic commands ###
