"""empty message

Revision ID: 559df8c33b9b
Revises: 4678f985a198
Create Date: 2013-11-23 15:25:27.229000

"""

# revision identifiers, used by Alembic.
revision = '559df8c33b9b'
down_revision = '4678f985a198'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('person_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'person_id')
    ### end Alembic commands ###
