"""empty message

Revision ID: f3b5810a35
Revises: 36cea0b2c9cf
Create Date: 2013-11-26 23:21:49.245000

"""

# revision identifiers, used by Alembic.
revision = 'f3b5810a35'
down_revision = '36cea0b2c9cf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('category_name', sa.String(length=10), nullable=True))
    op.drop_column('articles', u'category_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column(u'category_id', sa.INTEGER(), nullable=True))
    op.drop_column('articles', 'category_name')
    ### end Alembic commands ###
